.code
	ld r0, 0
;r1 holds the user input value 
	in r1, r0
;temp: 	ld r1, 1
	ld r2, 1
	ld r3, 0
;basically just load in r5 as the start of the loop
	ld r5, :LoopStart
	push r3
	push r2
:LoopStart
	pop r2
	pop r3
	add r4, r3, r2
	push r2
	push r4
	subi r1, 1
;if not done yet, jump back to the start of the loop
	brnz r5, r1
;load the output port into r0, then put the result there
	ld r0, 1
	out r0, r3
	halt